name: coronavirus
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fl_chart: ^0.8.7
  intl: ^0.16.1
  http: ^0.12.0+4
  google_fonts: ^0.3.10
  font_awesome_flutter: ^8.7.0
  url_launcher: ^5.4.2
  search_widget: ^1.0.2
  google_maps_flutter: ^0.5.21+6

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1



flutter:


  uses-material-design: true
  assets:
  -  assets/doc.png
  -  assets/family.png
  -  assets/friend.png
  -  assets/yoga.png
  - assets/login_logo.png
  - assets/my_logo.png




fonts:
  - family: WorkSansSemiBold
    fonts:
      - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

  - family: WorkSansBold
    fonts:
      - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

  - family: WorkSansMedium
    fonts:
      - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf


